---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add MongoDB apt key
    apt_key:
      url: http://www.mongodb.org/static/pgp/server-4.2.asc
      state: present
      
  - name: Add MongoDB repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present
      
  - name: Install MongoDB
    apt:
      name: mongodb-org
      update_cache: yes
      state: present
      
  - name: Enable MongoDB 
    systemd:
      name: mongod
      enabled: yes