---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  tasks:
  - name: Install ruby, bundler and git
    apt:
      pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
      state: "present"
      update_cache: true
      install_recommends: true